import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileSignature, Loader2, ShieldCheck } from "lucide-react";
import { useEffect, useRef } from "react";

export default function SignedPreviewDemo() {
  const demo = trpc.signatures.previewDemo.useMutation();
  const started = useRef(false);
  useEffect(() => { if (!started.current) { started.current = true; demo.mutate(); } }, [demo]);
  if (demo.isPending || !demo.data) return <div className="min-h-screen bg-[#f7f5ef] p-8"><div className="mx-auto grid max-w-4xl place-items-center rounded-[24px] border border-[#dce5d4] bg-[#fbfbf6] py-24"><Loader2 className="h-7 w-7 animate-spin text-[#628b3f]" /><p className="mt-4 text-[12px] text-[#647a71]">Gerando PDF assinado de demonstração…</p></div></div>;
  return <div className="min-h-screen bg-[#f7f5ef] p-5 md:p-8"><main className="mx-auto max-w-5xl space-y-5"><header className="rounded-[24px] bg-[#234a40] p-7 text-white"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#c9e26d] text-[#234a40]"><FileSignature className="h-5 w-5" /></span><div><p className="font-mono-ui text-[9px] uppercase tracking-[.16em] text-[#c9e26d]">Demonstração controlada</p><h1 className="mt-1 font-editorial text-[31px]">Documento aprovado e assinado</h1></div></div><p className="mt-4 max-w-2xl text-[12px] leading-6 text-[#cedcd5]">Esta visualização executa a assinatura institucional verificável sobre um PDF de demonstração, sem criar solicitação ou decisão no banco de dados.</p></header><section className="rounded-[22px] border border-[#dce5d4] bg-[#fbfbf6] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="flex items-center gap-2 text-[12px] font-bold text-[#35594b]"><CheckCircle2 className="h-4 w-4 text-[#5e883a]" />Assinatura institucional aplicada</p><p className="mt-1 font-mono-ui text-[9px] text-[#71847d]">{demo.data.signatureCode} · SHA-256 {demo.data.documentDigest.slice(0, 20)}…</p></div><Button asChild className="rounded-xl bg-[#234a40] text-[11px] hover:bg-[#173d36]"><a href={demo.data.signedPdfUrl} target="_blank" rel="noreferrer">Abrir PDF assinado</a></Button></div><div className="mt-5 overflow-hidden rounded-xl border border-[#dce5d4] bg-white"><iframe title="PDF assinado de demonstração" src={`${demo.data.signedPdfUrl}#view=FitH`} className="h-[720px] w-full" /></div><p className="mt-4 flex items-center gap-2 text-[10px] leading-5 text-[#7a6b35]"><ShieldCheck className="h-4 w-4 text-[#8b762c]" />A demonstração registra digest e código de verificação. Atos juridicamente vinculantes podem exigir certificado digital qualificado conforme a legislação aplicável.</p></section></main></div>;
}
