import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { roleLabels, userRoles, type UserRole } from "@shared/urbanDocs";
import { AlertTriangle, Bot, CheckCircle2, FileCheck2, ShieldCheck, UsersRound } from "lucide-react";

function AccessNotice() { return <div className="mx-auto max-w-2xl rounded-[20px] border border-[#dce5d4] bg-[#fbfbf6] p-8 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-[#6d9148]" /><h1 className="mt-4 font-editorial text-[31px] text-[#24473e]">Central de governança</h1><p className="mt-3 text-[12px] leading-6 text-[#71847e]">Esta área é destinada a revisores, aprovadores e administradores. Solicite a adequação do seu perfil para revisar sugestões de IA ou decidir emissões.</p></div>; }
const statusText = (status: string) => ({ pending: "Pendente", applied: "Aplicada", edited: "Editada", rejected: "Rejeitada", approved: "Aprovada", signed: "Assinado" }[status] ?? status);

export default function GovernanceCenter() {
  const { user } = useAuth();
  const canReview = user?.role === "reviewer" || user?.role === "approver" || user?.role === "admin";
  const canApprove = user?.role === "approver" || user?.role === "admin";
  const audits = trpc.ai.audits.useQuery(undefined, { enabled: canReview });
  const approvals = trpc.approvals.list.useQuery(undefined, { enabled: canReview });
  const signatures = trpc.signatures.list.useQuery(undefined, { enabled: canReview });
  const users = trpc.governance.users.useQuery(undefined, { enabled: user?.role === "admin" });
  const reviewAudit = trpc.ai.reviewAudit.useMutation({ onSuccess: () => audits.refetch() });
  const decide = trpc.approvals.decide.useMutation({ onSuccess: () => approvals.refetch() });
  const setRole = trpc.governance.setRole.useMutation({ onSuccess: () => users.refetch() });
  if (!canReview) return <AccessNotice />;
  return <div className="mx-auto max-w-[1320px] space-y-6"><header><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-[#6d865e]">Controle institucional</p><h1 className="mt-2 font-editorial text-[38px] tracking-[-.035em] text-[#24473e]">Governança e aprovação</h1><p className="mt-3 max-w-3xl text-[12px] leading-6 text-[#6b8078]">Revise as sugestões registradas pela IA, delibere emissões e mantenha uma trilha verificável de aprovação e assinatura.</p></header>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-[20px] border border-[#dce5d4] bg-[#fbfbf6] p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e6f0da] text-[#5a8038]"><Bot className="h-5 w-5" /></span><div><p className="font-mono-ui text-[9px] uppercase tracking-[.13em] text-[#77907f]">Auditoria de IA</p><h2 className="font-editorial text-[25px] text-[#294b40]">Histórico de sugestões</h2></div></div><div className="mt-5 space-y-3">{audits.data?.map((item) => <article key={item.id} className="rounded-xl border border-[#e0e8dd] bg-white p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold text-[#35584c]">{item.feature.replaceAll("_", " ")}</p><p className="mt-1 font-mono-ui text-[9px] text-[#80918a]">Registro #{item.id} · {new Date(item.createdAt).toLocaleString("pt-BR")}</p></div><span className="rounded-full bg-[#eff4e9] px-2 py-1 text-[9px] font-bold text-[#59763d]">{statusText(item.reviewStatus)}</span></div><p className="mt-3 line-clamp-3 text-[10px] leading-5 text-[#647a71]">{JSON.stringify(item.outputSnapshot)}</p>{item.reviewStatus === "pending" && <div className="mt-3 flex flex-wrap gap-2"><Button onClick={() => reviewAudit.mutate({ auditId: item.id, reviewStatus: "applied", reviewNote: "Revisado e considerado aplicável." })} disabled={reviewAudit.isPending} className="h-8 rounded-lg bg-[#234a40] text-[10px] hover:bg-[#173d36]">Aplicar</Button><Button onClick={() => reviewAudit.mutate({ auditId: item.id, reviewStatus: "rejected", reviewNote: "Sugestão não adotada após revisão humana." })} disabled={reviewAudit.isPending} variant="outline" className="h-8 rounded-lg border-[#d7e0d3] bg-white text-[10px]">Rejeitar</Button></div>}</article>)}{!audits.isLoading && !audits.data?.length && <p className="rounded-xl bg-[#f1f6eb] p-4 text-[11px] text-[#62796c]">Ainda não há sugestões de IA registradas.</p>}</div></section>
      <section className="rounded-[20px] border border-[#dce5d4] bg-[#fbfbf6] p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8eff2] text-[#446c7a]"><CheckCircle2 className="h-5 w-5" /></span><div><p className="font-mono-ui text-[9px] uppercase tracking-[.13em] text-[#77907f]">Emissões</p><h2 className="font-editorial text-[25px] text-[#294b40]">Histórico de aprovações</h2></div></div><div className="mt-5 space-y-3">{approvals.data?.map((item) => <article key={item.id} className="rounded-xl border border-[#e0e8dd] bg-white p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-bold text-[#35584c]">Emissão #{item.generatedDocumentId}</p><p className="mt-1 font-mono-ui text-[9px] text-[#80918a]">Solicitação #{item.requestId} · {new Date(item.createdAt).toLocaleString("pt-BR")}</p></div><span className="rounded-full bg-[#eff4e9] px-2 py-1 text-[9px] font-bold text-[#59763d]">{statusText(item.status)}</span></div>{item.decisionNote && <p className="mt-3 text-[10px] leading-5 text-[#647a71]">{item.decisionNote}</p>}{item.status === "pending" && (canApprove ? <div className="mt-3 flex gap-2"><Button onClick={() => decide.mutate({ approvalId: item.id, status: "approved", decisionNote: "Aprovado na central de governança." })} disabled={decide.isPending} className="h-8 rounded-lg bg-[#234a40] text-[10px] hover:bg-[#173d36]">Aprovar</Button><Button onClick={() => decide.mutate({ approvalId: item.id, status: "rejected", decisionNote: "Devolvido para ajustes na central de governança." })} disabled={decide.isPending} variant="outline" className="h-8 rounded-lg border-[#d7e0d3] bg-white text-[10px]">Devolver</Button></div> : <p className="mt-3 rounded-lg bg-[#f2f5ee] px-3 py-2 text-[10px] text-[#6f8178]">Seu perfil pode revisar, mas não aprovar emissões.</p>)}</article>)}{!approvals.isLoading && !approvals.data?.length && <p className="rounded-xl bg-[#f1f6eb] p-4 text-[11px] text-[#62796c]">Ainda não há emissões registradas.</p>}</div></section></div>
    <section className="rounded-[20px] border border-[#dce5d4] bg-[#fbfbf6] p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8f0de] text-[#597c38]"><FileCheck2 className="h-5 w-5" /></span><div><p className="font-mono-ui text-[9px] uppercase tracking-[.13em] text-[#77907f]">Integridade</p><h2 className="font-editorial text-[25px] text-[#294b40]">Livro de assinaturas</h2></div></div><div className="mt-5 space-y-3">{signatures.data?.map((item) => <article key={item.id} className="flex flex-col gap-2 rounded-xl border border-[#e0e8dd] bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-bold text-[#35584c]">Emissão #{item.generatedDocumentId} · {item.signerName}</p><p className="mt-1 font-mono-ui text-[9px] text-[#80918a]">{item.signatureCode} · {new Date(item.createdAt).toLocaleString("pt-BR")}</p></div><span className="rounded-full bg-[#e4f1d8] px-2 py-1 text-[9px] font-bold text-[#547637]">SHA-256 registrado</span></article>)}{!signatures.isLoading && !signatures.data?.length && <p className="rounded-xl bg-[#f1f6eb] p-4 text-[11px] text-[#62796c]">Nenhum documento foi assinado institucionalmente ainda.</p>}</div></section>
    {user?.role === "admin" && <section className="rounded-[20px] border border-[#dce5d4] bg-[#fbfbf6] p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eee9f7] text-[#635a83]"><UsersRound className="h-5 w-5" /></span><div><p className="font-mono-ui text-[9px] uppercase tracking-[.13em] text-[#77907f]">Acesso</p><h2 className="font-editorial text-[25px] text-[#294b40]">Níveis de usuário</h2></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-[#e0e8dd] font-mono-ui text-[9px] uppercase tracking-[.12em] text-[#83938c]"><th className="pb-3 font-medium">Usuário</th><th className="pb-3 font-medium">E-mail</th><th className="pb-3 font-medium">Papel</th><th className="pb-3" /></tr></thead><tbody>{users.data?.map((item) => <tr key={item.id} className="border-b border-[#edf1ea] last:border-0"><td className="py-3 text-[11px] font-bold text-[#36584d]">{item.name || "Sem identificação"}</td><td className="py-3 text-[10px] text-[#70847c]">{item.email || "—"}</td><td className="py-3"><Select value={item.role} onValueChange={(role) => setRole.mutate({ userId: item.id, role: role as UserRole })}><SelectTrigger className="h-8 w-36 rounded-lg border-[#d8e2d6] bg-white text-[10px]"><SelectValue /></SelectTrigger><SelectContent>{userRoles.map((role) => <SelectItem key={role} value={role}>{roleLabels[role]}</SelectItem>)}</SelectContent></Select></td><td className="py-3 text-right">{item.id === user.id && <span className="text-[9px] font-bold text-[#66844e]">Você</span>}</td></tr>)}</tbody></table></div></section>}
    <div className="rounded-xl border border-[#f1d9a9] bg-[#fff8e8] p-4 text-[10px] leading-5 text-[#7a631d]"><AlertTriangle className="mr-2 inline h-3.5 w-3.5" />A assinatura do UrbanDocs registra integridade e autoria institucional. Verifique a exigência de certificado digital qualificado para atos com força jurídica específica.</div>
  </div>;
}
