import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { documentTypeLabels, documentTypes, maxUploadBytes, type DocumentType } from "@shared/urbanDocs";
import { documentSchemas } from "@shared/documentFields";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Database, FileSearch2, FileText, Loader2, MapPinned, UploadCloud, WandSparkles } from "lucide-react";
import { ChangeEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";
import AIContextInsight from "./AIContextInsight";
import DocumentFinalPreview, { type FinalDocumentOutput } from "./DocumentFinalPreview";
import DocumentTypeFields from "./DocumentTypeFields";
import FileExtractionReview, { type FileExtractionCard } from "./FileExtractionReview";
import LotGeometryMap from "./LotGeometryMap";
import UrbanAIReview from "./UrbanAIReview";

type LocalUpload = { file: File; kind: "input" | "spatial" };
type Output = FinalDocumentOutput;

function serializeFile(file: File): Promise<{ filename: string; mimeType: string; contentBase64: string }> {
  return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error("Não foi possível ler o arquivo.")); reader.onload = () => resolve({ filename: file.name, mimeType: file.type || "application/octet-stream", contentBase64: String(reader.result).split(",")[1] ?? "" }); reader.readAsDataURL(file); });
}

function isAllowed(file: File, spatial: boolean) { const extension = file.name.split(".").pop()?.toLowerCase() ?? ""; return spatial ? ["xlsx", "xls", "csv", "gpkg"].includes(extension) : ["pdf", "docx", "doc", "dwg", "jpg", "jpeg", "png"].includes(extension); }
function DynamicField({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="space-y-2"><Label className="text-[11px] font-bold text-[#406055]">{label}</Label><Input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="h-11 rounded-xl border-[#d6dfd4] bg-white text-[12px]" /></div>; }

export default function RequestWizardWithMap() {
  const [, setLocation] = useLocation();
  const [step, setStep] = useState(1);
  const [type, setType] = useState<DocumentType>(() => { const requested = new URLSearchParams(window.location.search).get("tipo"); return requested && documentTypes.includes(requested as DocumentType) ? requested as DocumentType : documentTypes[0]; });
  const [protocol, setProtocol] = useState(""); const [enrollment, setEnrollment] = useState(""); const [applicant, setApplicant] = useState(""); const [description, setDescription] = useState("");
  const [fields, setFields] = useState<Record<string, string>>({}); const [requestId, setRequestId] = useState<number>(); const [uploads, setUploads] = useState<LocalUpload[]>([]); const [extracted, setExtracted] = useState<Record<string, unknown>>({}); const [analyses, setAnalyses] = useState<FileExtractionCard[]>([]); const [output, setOutput] = useState<Output>();
  const create = trpc.requests.create.useMutation(); const update = trpc.requests.update.useMutation(); const uploadRequest = trpc.uploads.requestFile.useMutation(); const uploadSpatial = trpc.spatial.upload.useMutation(); const analyzeFile = trpc.uploads.analyzeRequestFile.useMutation(); const applyExtraction = trpc.requests.applyFileExtraction.useMutation(); const crossReference = trpc.spatial.crossReference.useMutation(); const markReady = trpc.requests.markReadyForReview.useMutation(); const generate = trpc.generated.create.useMutation();
  const { data: spatialSources = [] } = trpc.spatial.list.useQuery();
  const busy = create.isPending || update.isPending || uploadRequest.isPending || uploadSpatial.isPending || analyzeFile.isPending || applyExtraction.isPending || crossReference.isPending || markReady.isPending || generate.isPending;
  const activeUploads = useMemo(() => ({ input: uploads.filter((item) => item.kind === "input"), spatial: uploads.filter((item) => item.kind === "spatial") }), [uploads]);
  const activeGeoPackages = useMemo(() => spatialSources.filter((source) => source.kind === "geopackage" && source.isActive), [spatialSources]);
  const geometry = extracted.geometry as { type: string; coordinates: unknown } | undefined;
  const labels = ["Cadastro", "Anexos", "Revisão", "Mapa", "Emissão"];

  const fillForTest = () => { const sample = { protocol: "TESTE/2026", enrollment: "00.000.000.0000.000", applicant: "Interessado de teste", description: "Solicitação para conferência do fluxo." }; setProtocol(sample.protocol); setEnrollment(sample.enrollment); setApplicant(sample.applicant); setDescription(sample.description); toast.info("Dados mínimos de teste preenchidos. A etapa de anexos pode complementar os campos."); };
  const addFiles = (event: ChangeEvent<HTMLInputElement>, kind: LocalUpload["kind"]) => { const incoming = Array.from(event.target.files ?? []); const invalid = incoming.find((file) => !isAllowed(file, kind === "spatial") || file.size > maxUploadBytes); event.target.value = ""; if (invalid) return toast.error(`Verifique o formato e o limite de 25 MB de “${invalid.name}”.`); setUploads((current) => [...current, ...incoming.map((file) => ({ file, kind }))]); };
  const createRequest = async () => { if (!protocol.trim()) return toast.error("Informe um protocolo ou número de referência para iniciar a solicitação."); try { const request = await create.mutateAsync({ protocol, documentType: type, enrollment: enrollment || undefined, applicant: applicant || undefined, description: description || undefined, formData: fields }); if (!request) throw new Error("Solicitação não criada."); setRequestId(request.id); setStep(2); toast.success("Solicitação iniciada. Anexe documentos para extrair e revisar os campos."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível iniciar a solicitação."); } };
  const uploadAndAnalyze = async () => { if (!requestId) return; try { const cards: FileExtractionCard[] = []; for (const { file } of activeUploads.input) { const stored = await uploadRequest.mutateAsync({ requestId, payload: await serializeFile(file) }); const result = await analyzeFile.mutateAsync({ requestId, fileId: stored.id }); cards.push({ fileId: stored.id, filename: file.name, ...result.analysis }); } for (const { file } of activeUploads.spatial) await uploadSpatial.mutateAsync({ name: file.name.replace(/\.[^.]+$/, ""), payload: await serializeFile(file) }); setAnalyses(cards); setStep(3); toast.success(cards.length ? "Anexos analisados. Revise cada sugestão antes de continuar." : "Insumos registrados. Complete a revisão manualmente antes de continuar."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível processar os anexos."); } };
  const syncAppliedFields = (patch: Record<string, string>) => { if (patch.protocolo) setProtocol(patch.protocolo); if (patch.inscricao_imobiliaria) setEnrollment(patch.inscricao_imobiliaria); if (patch.interessado) setApplicant(patch.interessado); if (patch.objeto) setDescription(patch.objeto); const schemaKeys = new Set(documentSchemas[type].fields.map((field) => field.key)); setFields((current) => ({ ...current, ...Object.fromEntries(Object.entries(patch).filter(([key]) => schemaKeys.has(key))) })); };
  const applySuggestions = async (patch: Record<string, string>) => { if (!requestId) return; try { await applyExtraction.mutateAsync({ id: requestId, fields: patch }); syncAppliedFields(patch); toast.success("Campos revisados e aplicados ao processo."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível aplicar os campos."); throw error; } };
  const reviewAndCross = async () => { if (!requestId) return; try { const missing = documentSchemas[type].fields.filter((field) => field.required && !fields[field.key]?.trim()).map((field) => field.label); if (missing.length) return toast.error(`Revise os campos obrigatórios antes do cruzamento: ${missing.join(", ")}.`); await update.mutateAsync({ id: requestId, protocol, enrollment: enrollment || undefined, applicant: applicant || undefined, description: description || undefined, formData: fields }); const result = await crossReference.mutateAsync({ requestId }); setExtracted((result.extractedData as Record<string, unknown>) ?? {}); setStep(4); if (result.sourceFailures.length) toast.warning("O cruzamento foi concluído com alertas em algumas fontes. Confira o mapa e os dados."); else toast.success("Dados revisados e cruzamento territorial concluído."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível concluir a revisão."); } };
  const prepareEmission = async () => { if (!requestId) return; try { await markReady.mutateAsync({ id: requestId }); setStep(5); toast.success("Processo pronto para emissão. Confira os dados consolidados antes de gerar a versão documental."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível preparar a emissão."); } };
  const produce = async () => { if (!requestId) return; try { const result = await generate.mutateAsync({ requestId }); setOutput({ docx: { storageUrl: result.docx.storageUrl }, pdf: { storageUrl: result.pdf.storageUrl }, generatedDocumentId: result.generated.id, approvalId: result.approval.id }); toast.success("DOCX e PDF gerados com o modelo ativo e os dados revisados."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível gerar os documentos."); } };
  const next = () => { if (step === 1) void createRequest(); else if (step === 2) void uploadAndAnalyze(); else if (step === 3) void reviewAndCross(); else if (step === 4) void prepareEmission(); else if (step === 5 && !output) void produce(); };
  const percent = [20, 40, 60, 80, 100][step - 1];

  return <div className="mx-auto max-w-[1180px] space-y-7 pb-24"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.17em] text-[#627d5b]">Nova instrução</p><h1 className="mt-2 font-editorial text-[34px] tracking-[-.035em] text-[#1d3933] md:text-[42px]">Nova solicitação</h1><p className="mt-3 max-w-2xl text-[13px] leading-6 text-[#69807a]">Siga da identificação aos anexos, à revisão humana, ao cruzamento territorial e à emissão no modelo oficial.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={step !== 1 || busy} onClick={fillForTest} className="rounded-xl border-[#cbdabb] bg-[#f5f8ed] text-xs font-bold text-[#557739] hover:bg-[#edf4df]"><WandSparkles className="mr-2 h-4 w-4" />Preencher para teste</Button><Button variant="outline" onClick={() => setLocation("/")} className="rounded-xl border-[#d8e0d6] bg-[#fcfbf7] text-xs text-[#426055]">Salvar e sair</Button></div></div><div className="rounded-[18px] border border-[#dce4d8] bg-[#fbfbf6] px-5 py-4"><div className="mb-3 flex justify-between font-mono-ui text-[9px] uppercase tracking-[.14em] text-[#769087]"><span>Etapa {step} de 5</span><span>{percent}% concluído</span></div><Progress value={percent} className="h-1.5 bg-[#e3e9dd] [&>div]:bg-[#7ea64f]" /><div className="mt-4 grid grid-cols-5">{labels.map((label, index) => <div key={label} className={`text-[9px] font-semibold sm:text-[10px] ${index + 1 <= step ? "text-[#42682d]" : "text-[#8fa097]"}`}><span className={`mb-2 grid h-5 w-5 place-items-center rounded-full border text-[9px] ${index + 1 < step ? "border-[#7da74d] bg-[#7da74d] text-white" : index + 1 === step ? "border-[#7da74d] bg-[#e9f3db] text-[#4d742e]" : "border-[#ccd8cb] bg-white"}`}>{index + 1 < step ? <Check className="h-3 w-3" /> : index + 1}</span>{label}</div>)}</div></div>
    {step === 1 && <div className="grid gap-5 lg:grid-cols-[1fr_.72fr]"><section className="rounded-[20px] border border-[#dde4d9] bg-[#fcfbf7] p-6"><h2 className="font-editorial text-[27px] tracking-[-.03em] text-[#213e37]">Identificação inicial</h2><p className="mt-2 text-[11px] leading-5 text-[#6e8179]">Você pode iniciar com o protocolo e completar os demais campos a partir dos arquivos enviados na próxima etapa.</p><div className="mt-6 space-y-5"><div className="space-y-2"><Label className="text-[11px] font-bold text-[#406055]">Tipo de documento</Label><Select value={type} onValueChange={(value) => { setType(value as DocumentType); setFields({}); }}><SelectTrigger className="h-11 rounded-xl border-[#d6dfd4] bg-white text-[12px]"><SelectValue /></SelectTrigger><SelectContent>{documentTypes.map((item) => <SelectItem key={item} value={item}>{documentTypeLabels[item]}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-5 sm:grid-cols-2"><DynamicField label="Número do protocolo" value={protocol} onChange={setProtocol} placeholder="Ex.: 2026/000148" /><DynamicField label="Inscrição imobiliária" value={enrollment} onChange={setEnrollment} placeholder="Pode ser extraída dos anexos" /></div><DynamicField label="Interessado ou requerente" value={applicant} onChange={setApplicant} placeholder="Pode ser extraído dos anexos" /><div className="space-y-2"><Label className="text-[11px] font-bold text-[#406055]">Objeto da solicitação</Label><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Pode ser complementado pelos documentos enviados." className="min-h-24 rounded-xl border-[#d6dfd4] bg-white text-[12px]" /></div></div><UrbanAIReview documentType={type} protocol={protocol} enrollment={enrollment} applicant={applicant} description={description} fields={fields} extractedData={extracted} onApplyDraft={setDescription} /></section><aside className="rounded-[20px] bg-[#234a40] p-6 text-white"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#c9e26d] text-[#21423a]"><FileText className="h-5 w-5" /></span><p className="mt-7 font-mono-ui text-[10px] uppercase tracking-[.16em] text-[#c9e26d]">tipologia selecionada</p><h3 className="mt-3 font-editorial text-[29px] leading-[1.05] tracking-[-.03em]">{documentTypeLabels[type]}</h3><p className="mt-4 text-[11px] leading-5 text-[#cfddd5]">{documentSchemas[type].summary}</p><div className="mt-7 rounded-xl border border-white/10 bg-black/10 p-3 text-[10px] leading-5 text-[#d3e0da]"><p className="font-mono-ui text-[8px] uppercase tracking-[.13em] text-[#c9e26d]">Fluxo contínuo</p><p className="mt-2">O processo mantém a mesma identificação até a emissão. Os anexos sugerem campos, a pessoa revisa, o mapa consolida e a emissão usa o modelo ativo.</p></div></aside></div>}
    {step === 2 && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-[20px] border border-[#dde4d9] bg-[#fcfbf7] p-6"><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-[#72887c]">01. Documentação de apoio</p><h2 className="mt-2 font-editorial text-[28px] text-[#213e37]">Anexar e analisar</h2><p className="mt-2 text-[11px] leading-5 text-[#708179]">PDF, imagens e documentos são lidos para sugerir campos. DWG usa metadados textuais e exige conferência técnica de geometria e escala.</p><label className="mt-6 flex cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-[#b6c8b9] bg-[#f8faf4] px-5 py-8 text-center"><input type="file" className="sr-only" accept=".pdf,.docx,.doc,.dwg,.jpg,.jpeg,.png" multiple onChange={(event) => addFiles(event, "input")} /><UploadCloud className="h-5 w-5 text-[#5d853b]" /><p className="mt-3 text-[12px] font-bold text-[#365d50]">Adicionar documentos, imagens e projetos</p><p className="mt-1 text-[10px] text-[#758982]">PDF, DOCX, DOC, DWG, JPG, JPEG ou PNG; até 25 MB por arquivo.</p></label><div className="mt-4 space-y-2">{activeUploads.input.map(({ file }) => <div key={`${file.name}-${file.lastModified}`} className="rounded-lg bg-[#f1f5ec] px-3 py-2 text-[10px] text-[#4d6a5f]">{file.name}</div>)}</div></section><section className="rounded-[20px] border border-[#dde4d9] bg-[#fcfbf7] p-6"><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-[#72887c]">02. Referências territoriais</p><h2 className="mt-2 font-editorial text-[28px] text-[#213e37]">Bases de consulta</h2><div className="mt-5 rounded-xl border border-[#d8e5d1] bg-[#f3f8ec] px-4 py-3 text-[10px] leading-5 text-[#567247]"><p className="font-bold">Base padrão: GeoPackage do aplicativo EIV</p><p className="mt-1">{activeGeoPackages.length ? `${activeGeoPackages.length} GeoPackage(s) ativo(s) serão consultados após a revisão dos campos.` : "Nenhum GeoPackage ativo foi localizado. Você pode anexar uma base para a consulta territorial."}</p></div><label className="mt-4 flex cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-[#b6c8b9] bg-[#f8faf4] px-5 py-8 text-center"><input type="file" className="sr-only" accept=".xlsx,.xls,.csv,.gpkg" multiple onChange={(event) => addFiles(event, "spatial")} /><Database className="h-5 w-5 text-[#5d853b]" /><p className="mt-3 text-[12px] font-bold text-[#365d50]">Adicionar planilha ou GeoPackage</p><p className="mt-1 text-[10px] text-[#758982]">A consulta será feita após a confirmação dos dados revisados.</p></label><div className="mt-4 space-y-2">{activeUploads.spatial.map(({ file }) => <div key={`${file.name}-${file.lastModified}`} className="rounded-lg bg-[#f1f5ec] px-3 py-2 text-[10px] text-[#4d6a5f]">{file.name}</div>)}</div></section></div>}
    {step === 3 && <div className="space-y-5"><section className="rounded-[20px] border border-[#dde4d9] bg-[#fcfbf7] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-[#72887c]">Revisão humana</p><h2 className="mt-2 font-editorial text-[28px] text-[#213e37]">Conferir dados antes do mapa</h2><p className="mt-2 text-[11px] leading-5 text-[#708179]">A análise nunca preenche o processo sem sua confirmação. Revise sugestões, altere valores quando necessário e complete os campos obrigatórios.</p></div><span className="inline-flex items-center gap-1 rounded-full bg-[#eff6e9] px-3 py-1.5 text-[10px] font-bold text-[#567a37]"><FileSearch2 className="h-3.5 w-3.5" />{analyses.length} arquivo(s) analisado(s)</span></div><div className="mt-5 space-y-3">{analyses.map((item) => <FileExtractionReview key={item.fileId} item={item} onApply={applySuggestions} disabled={busy} />)}{!analyses.length && <p className="rounded-xl bg-[#f4f7f0] px-4 py-3 text-[11px] text-[#74847c]">Nenhuma sugestão automática foi criada. Preencha os campos manualmente para continuar.</p>}</div><div className="mt-6 grid gap-5 sm:grid-cols-2"><DynamicField label="Número do protocolo" value={protocol} onChange={setProtocol} placeholder="Protocolo" /><DynamicField label="Inscrição imobiliária" value={enrollment} onChange={setEnrollment} placeholder="Inscrição" /><DynamicField label="Interessado ou requerente" value={applicant} onChange={setApplicant} placeholder="Interessado" /><DynamicField label="Empreendimento ou objeto" value={fields.empreendimento ?? ""} onChange={(value) => setFields((current) => ({ ...current, empreendimento: value }))} placeholder="Empreendimento" /></div><div className="mt-5"><DocumentTypeFields type={type} fields={fields} onChange={(key, value) => setFields((current) => ({ ...current, [key]: value }))} /></div></section></div>}
    {step === 4 && <div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><section className="rounded-[20px] border border-[#dde4d9] bg-[#fcfbf7] p-6"><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-[#72887c]">Conferência territorial</p><h2 className="mt-2 font-editorial text-[28px] text-[#213e37]">Dados consolidados</h2><dl className="mt-5 divide-y divide-[#e6ebe1]">{Object.entries(extracted).filter(([key]) => key !== "geometry").slice(0, 12).map(([key, value]) => <div key={key} className="flex items-center justify-between gap-5 py-3 text-[11px]"><dt className="capitalize text-[#758780]">{key.replaceAll("_", " ")}</dt><dd className="max-w-[55%] truncate text-right font-medium text-[#35574b]">{typeof value === "object" ? JSON.stringify(value) : String(value)}</dd></div>)}{Object.keys(extracted).length === 0 && <p className="py-8 text-[11px] leading-5 text-[#72847b]">Nenhuma correspondência territorial foi encontrada. O processo pode avançar, mas a emissão deve registrar a conferência técnica necessária.</p>}</dl></section><section><LotGeometryMap geometry={geometry} enrollment={enrollment} /></section></div>}
    {step === 5 && <div className="space-y-5">{output ? <DocumentFinalPreview output={output} /> : <><AIContextInsight scope="final_review" title="Conferência assistida da emissão" context={`Há uma solicitação pronta para emissão da tipologia ${documentTypeLabels[type]}. Oriente uma conferência de dados, anexos e pendências antes de gerar a versão no modelo ativo.`} /><section className="rounded-[20px] border border-[#d9e5d5] bg-[#fafff7] p-6"><div className="flex gap-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f2da] text-[#5c8238]"><CheckCircle2 className="h-5 w-5" /></span><div><h2 className="font-editorial text-[28px] text-[#213e37]">Pronto para emitir</h2><p className="mt-2 text-[11px] leading-5 text-[#708179]">A emissão utilizará o modelo DOCX ativo, mantendo corpo, cabeçalho e rodapé. O PDF será convertido a partir do mesmo DOCX preenchido.</p></div></div></section></>}</div>}
    <div className="flex items-center justify-between"><Button variant="ghost" disabled={step === 1 || busy} onClick={() => setStep((current) => current - 1)} className="text-xs text-[#54726a]"><ArrowLeft className="mr-1.5 h-4 w-4" />Voltar</Button>{(!output || step < 5) && <Button disabled={busy} onClick={next} className="h-11 rounded-xl bg-[#234a40] px-5 text-xs hover:bg-[#173d36]">{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : step === 5 ? <WandSparkles className="mr-2 h-4 w-4" /> : step === 4 ? <MapPinned className="mr-2 h-4 w-4" /> : null}{step === 1 ? "Registrar e continuar" : step === 2 ? "Analisar anexos" : step === 3 ? "Revisar e cruzar dados" : step === 4 ? "Preparar emissão" : "Gerar DOCX e PDF"}<ArrowRight className="ml-2 h-4 w-4" /></Button>}</div>
  </div>;
}
